name: Email Reminder Cron Job

on:
  schedule:
    - cron: '*/60 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual run

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode credentials.json and token.json
        env:
          CREDENTIALS_JSON_B64: ${{ secrets.CREDENTIALS_JSON_B64 }}
          TOKEN_JSON_B64: ${{ secrets.TOKEN_JSON_B64 }}
        run: |
          echo "$CREDENTIALS_JSON_B64" | base64 --decode > credentials.json
          echo "$TOKEN_JSON_B64" | base64 --decode > token.json

      - name: Run email reminder script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          AIRTABLE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AIRTABLE_PERSONAL_ACCESS_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }} 
          
        run: python cron_email_sender.py
